### ISSUE TITLE
Whether to open source the code for integrating GNSS?

### ISSUE THREAD

**Issue by MasterY0416** [zijiechenrobotics/ig_lio#11]
Hi author, I ran your code and it worked great. Although this is not the focus of the article, I saw the code interface for fused GNSS sensors. Will the relevant code be open sourced later?

**Comment by zijiechenrobotics** [comment]
Thank you for your interest in this work.
The `SyncMeasurements` function is copied from another ongoing multi-sensor fusion system. The system will be released in the future.
