### ISSUE TITLE
协方差更新

### ISSUE THREAD

**Issue by liangheming** [zijiechenrobotics/ig_lio#13]
1. lio.cpp中ComputeFinalCovariance方法中更新协方差`P_ = L * temp_P * L`是不是少了一个转置 
2. 另外论文中的公式(8)的 协方差的计算，分母是不是应该是N-1

最后非常感谢作者的开源工作

**Comment by zijiechenrobotics** [comment]
Sorry for replying late since GitHub doesn't push messages to my email!
You are right and thank you for returning the bugs to me :thumbsup:
