### ISSUE TITLE
Proposal to Add Point Cloud Map Saving Feature

### ISSUE THREAD

**Issue by KurokoWD** [zijiechenrobotics/ig_lio#15]
Thanks to your excellent work!

I believe that adding a feature to save point cloud maps as .PCD file would make it even more powerful and useful. Such a feature would enable users to conveniently save and manage point cloud data.

Thank you for your time and effort!

**Comment by zijiechenrobotics** [comment]
Sorry for replying late since GitHub doesn't push messages to my email!
Your request is on my to-do list. I will add this feature to my next commit.

**Comment by 85256638** [comment]
> Sorry for replying late since GitHub doesn't push messages to my email! Your request is on my to-do list. I will add this feature to my next commit.

hi there, thanks for the great work, will you still plan to implement this feature? it would be a massive help.
