### ISSUE TITLE
亲爱的B友，可以给个paper的pdf吗？没有IEEE的会员

### ISSUE THREAD

**Issue by Nothand0212** [zijiechenrobotics/ig_lio#2]
亲爱的B友，可以给个paper的pdf吗？没有IEEE的会员。
祝你成果多多~ღ( ´･ᴗ･` )比心

**Comment by zijiechenrobotics** [comment]
Thank you for your interest in this work. The PDF has been released to the Github page: https://github.com/zijiechenrobotics/ig_lio/blob/main/ig_lio_early_access.pdf
