### ISSUE TITLE
开发在已构建点云地图上定位的代码

### ISSUE THREAD

**Issue by MasterY0416** [zijiechenrobotics/ig_lio#21]
作者你好，我在算法运行之初，使用voxel_map_ptr_->AddCloud(PCDCloudGMap);将事先建好的地图存入到Voxelmap中，然后通过给定初值，实现在已知地图上定位的功能。但是我发现通过ComputeHashIndex无法为当前帧的点云在地图中很好的找到对应的索引，或者说，在同一个位置，SLAM过程中voxel_map_ptr_的hashidx，和定位中的hashidx没有一样的，请问有什么好的办法吗？

**Comment by Luo1imasi** [comment]
请问您解决这个问题了吗
