### ISSUE TITLE
How can I save the global map

### ISSUE THREAD

**Issue by libaiwanovo** [zijiechenrobotics/ig_lio#32]
Thank you for your team's wonderful workt! How can I save the global map?

**Comment by alwynmathew** [comment]
@libaiwanovo, how did you save the global map?

**Comment by libaiwanovo** [comment]
> @libaiwanovo, how did you save the global map?，你是怎么保存全球地图的？

You can use the following command in the terminal:
rosservice call /save_map “save_path: ‘you_pcd_save_path.pcd’
resolution: 0.0”

**Comment by alwynmathew** [comment]
@libaiwanovo `/save_map` service is not available.

**Comment by libaiwanovo** [comment]
1, Did you do source devel/setup.bash before running the package?
2, Did you exit the rviz that built the map before running map_sever?

**Comment by 85256638** [comment]
> 1, Did you do source devel/setup.bash before running the package? 2, Did you exit the rviz that built the map before running map_sever?

I had the same error as alwynmathew, `/save_map service is not available`

1. I sourced the devel/setup.bash
2. If i exit the rviz, it throws new error something like: `Failed to contact master`

@alwynmathew did you solve this eventually?
