### ISSUE TITLE
PCD Scan Save 

### ISSUE THREAD

**Issue by kushantp58** [zijiechenrobotics/ig_lio#36]
How do you save scans like you could do it for LIO SLAMs ? 

I tried using this in config.yaml - 
`pcd_save: interval: -1`
  `pcd_save_en: true`
  
  Didn't work, any help would be appreciated !

**Comment by kushantp58** [comment]
Never mind, figured it out using pcl-ros. Thanks !!

**Comment by alwynmathew** [comment]
@kushantp58, how did you save the scan?

**Comment by kushantp58** [comment]
So you use pcl_ros to save it .

1. Install it using `sudo apt intall ros-noetic-pcl-ros` .
2. Start the slam and use this:  `rosrun pcl_ros pointcloud_to_pcd input:=/current_scan`
3. This will save pcd scans in that particular directory
4. Now you will have all the scans, you can either merge them to get a .ply file (I've written a script for this if you want)

**Comment by alwynmathew** [comment]
Thank you @kushantp58. I did record each scan with pcl_ros, but will the resultant merged scan have redundant points? Please share the script.

**Comment by kushantp58** [comment]
``import open3d as o3d
import os , re

#check the current working directory
print("Current working directory: ", os.getcwd())
print("Changing working directory to the data folder ...")
print("Testing IO for point cloud ...")
folder = "/home/kuspatel/data/2024_07_09_15_38_45/2024_07_09_15_38_45/ig_lio/scans/" #replace this with your folder name
#iterate through directory
pcds = []
for file in os.listdir(folder):
    if file.endswith(".pcd"):
        print("Reading file: ", file)
        pcds.append(file)


print("Saving concatenated point cloud ...")
#convert it into a single point cloud
pd = o3d.geometry.PointCloud()
for file in pcds:
    pcd_temp = o3d.io.read_point_cloud(folder + file)
    pd += pcd_temp

#save the point cloud to a ply file
o3d.io.write_point_cloud(folder + "merged.ply", pd)
``
