### ISSUE TITLE
为什么不需要滑窗和边缘化呢

### ISSUE THREAD

**Issue by Torchmm** [zijiechenrobotics/ig_lio#6]
您好，我运行了您的代码库，效果很不错，但是如题，为什么您的紧耦合方案不需要滑窗和边缘化呢？

**Comment by zijiechenrobotics** [comment]
Thank you for trying this work!
This work uses a fixed-lag smoother with a single moment, equivalent to the IESKF. One can simply consider that the marginalization constraint combined with the IMU integration generates the IMU constraint in MAP estimation.

**Comment by Torchmm** [comment]
thanks for your reply!
